---
- hosts: all
  tasks: 
    - name: check the folder
      shell: (cd /tmp/template; find . -maxdepth 1 -type f) | cut -d'/' -f2
      register: files_to_copy
    - name: fetch module
      fetch: src=/tmp/template/{{ item }} dest=/tmp/test/
      with_items: "{{ files_to_copy.stdout_lines }}"
