--- 
- 
  hosts: all
  remote_user: root
 
  name: "Include vars"
  tasks: 
    - 
      name: "Ansible Template Example"
      template: 
        dest: /root/hello_world.txt
        src: hello_world.j2
  vars:
 #  variable_to_be_replaced: 'Hello world'
  vars_files:
    - UAT.json 
