---
- hosts: all
  tasks: 
  #   - name: check the folder
  #    shell: (cd /tmp/; find . -maxdepth 1 -type d) | cut -d'/' -f2
  #    register: files_to_copy
  #  - name: fetch module
  #    fetch: src=/tmp/{{ item }} dest=/tmp/test/
  #    with_items: "{{ files_to_copy.stdout_lines }}"
      - name: syncronized module 
        synchronize:
          mode: pull
          src: /tmp/
          dest: /tmp/template/
