---
 - hosts: all
   remote_user: root
   vars_files:
          - json/UAT.json

   tasks:
     -
       name: "Ansible Template Example"
       template:
         src: /root/nam/test.j2
         dest: /tmp/test.properties
         template_host: 3.136.116.31
         remote_src: yes 
         owner: root
         group: root
         mode: 0644
         become: true
         become_user: root

