--- 
- 
  hosts: localhost
  remote_user: root
  vars_files:
          - json/UAT.json
          - json/DEV.json
 
  tasks: 
    - 
      name: "Ansible Template Example"
      template: 
        dest: /tmp/{{item}}.txt
        src: test.j2
      with_items:
              - file1
              - file2
  
   
  
