---
 - name: copy a file 
   copy:
           src: pb3.yml
           dest: /opt/pb3.yml
 - name: clone a private repository
   git: 
      repo: https://github.com/JJSWAIN2018/Ansible.git
      #key_file=/root/.ssh/id_rsa.github
      dest: /opt/example
# tasks file for test-role-1
